#!/usr/bin/env Rscript

args <- commandArgs(TRUE)

dataScript <- args[1]
source(paste0("data/",dataScript))  ## Defines clusterings

library(sdols)
pp <- expectedPairwiseAllocationMatrix(clusterings)

files <- system2("find",c(paste0("out/",dataScript),"-name","'*.Rd'"),stdout=TRUE)
clean <- function(x) {
  y <- strsplit(system2("basename",c(x,".Rd"),stdout=TRUE),"-")
  paste(c(y[[1]][1],paste(y[[1]][-1],collapse="-")),collapse=" ")
}

for ( f in files ) {
  load(f)
  cat(clean(f))
  cat(" ")
  cat(paste(unname(unlist(latentStructureFit(estimate,pp))[3:4])))
  cat(" ")
  cat(time[3])
  cat("\n")
}

